[2024-06-30 08:16:15,875] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-06-29T00:00:00+00:00 [queued]>
[2024-06-30 08:16:15,884] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-06-29T00:00:00+00:00 [queued]>
[2024-06-30 08:16:15,885] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-06-30 08:16:15,885] {taskinstance.py:1088} INFO - Starting attempt 2 of 4
[2024-06-30 08:16:15,885] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-06-30 08:16:15,902] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_zero> on 2024-06-29T00:00:00+00:00
[2024-06-30 08:16:15,907] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_zero', '2024-06-29T00:00:00+00:00', '--job-id', '9', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmpb4an3351', '--error-file', '/tmp/tmpy0eg6xhg']
[2024-06-30 08:16:15,905] {standard_task_runner.py:52} INFO - Started process 2596 to run task
[2024-06-30 08:16:15,908] {standard_task_runner.py:77} INFO - Job 9: Subtask task_zero
[2024-06-30 08:16:15,936] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_zero 2024-06-29T00:00:00+00:00 [running]> on host 2532fdaf14cb
[2024-06-30 08:16:15,972] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_zero
AIRFLOW_CTX_EXECUTION_DATE=2024-06-29T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-06-29T00:00:00+00:00
[2024-06-30 08:16:15,973] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2024-06-30 08:16:15,974] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'pip install beautifulsoup4']
[2024-06-30 08:16:15,979] {subprocess.py:75} INFO - Output:
[2024-06-30 08:16:16,743] {subprocess.py:79} INFO - Defaulting to user installation because normal site-packages is not writeable
[2024-06-30 08:16:16,803] {subprocess.py:79} INFO - Requirement already satisfied: beautifulsoup4 in /home/***/.local/lib/python3.6/site-packages (4.12.3)
[2024-06-30 08:16:16,809] {subprocess.py:79} INFO - Requirement already satisfied: soupsieve>1.2 in /home/***/.local/lib/python3.6/site-packages (from beautifulsoup4) (2.3.2.post1)
[2024-06-30 08:16:20,413] {subprocess.py:83} INFO - Command exited with return code 0
[2024-06-30 08:16:20,436] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=assignment, task_id=task_zero, execution_date=20240629T000000, start_date=20240630T081615, end_date=20240630T081620
[2024-06-30 08:16:20,457] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-30 08:16:20,493] {local_task_job.py:151} INFO - Task exited with return code 0
