[2025-03-16 06:48:30,222] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-11-27T00:00:00+00:00 [queued]>
[2025-03-16 06:48:30,244] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-11-27T00:00:00+00:00 [queued]>
[2025-03-16 06:48:30,245] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2025-03-16 06:48:30,245] {taskinstance.py:1088} INFO - Starting attempt 1 of 3
[2025-03-16 06:48:30,246] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2025-03-16 06:48:30,256] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_zero> on 2024-11-27T00:00:00+00:00
[2025-03-16 06:48:30,262] {standard_task_runner.py:52} INFO - Started process 71 to run task
[2025-03-16 06:48:30,271] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_zero', '2024-11-27T00:00:00+00:00', '--job-id', '39', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmp1nyi7c41', '--error-file', '/tmp/tmp9sigdxgu']
[2025-03-16 06:48:30,271] {standard_task_runner.py:77} INFO - Job 39: Subtask task_zero
[2025-03-16 06:48:30,348] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_zero 2024-11-27T00:00:00+00:00 [running]> on host 4ecec8cb0ca2
[2025-03-16 06:48:30,417] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_zero
AIRFLOW_CTX_EXECUTION_DATE=2024-11-27T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-11-27T00:00:00+00:00
[2025-03-16 06:48:30,418] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2025-03-16 06:48:30,419] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'pip install beautifulsoup4']
[2025-03-16 06:48:30,430] {subprocess.py:75} INFO - Output:
[2025-03-16 06:48:31,444] {subprocess.py:79} INFO - Defaulting to user installation because normal site-packages is not writeable
[2025-03-16 06:48:31,570] {subprocess.py:79} INFO - Requirement already satisfied: beautifulsoup4 in /home/***/.local/lib/python3.6/site-packages (4.12.3)
[2025-03-16 06:48:31,582] {subprocess.py:79} INFO - Requirement already satisfied: soupsieve>1.2 in /home/***/.local/lib/python3.6/site-packages (from beautifulsoup4) (2.3.2.post1)
[2025-03-16 06:48:36,366] {subprocess.py:83} INFO - Command exited with return code 0
[2025-03-16 06:48:36,401] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=assignment, task_id=task_zero, execution_date=20241127T000000, start_date=20250316T064830, end_date=20250316T064836
[2025-03-16 06:48:36,433] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-16 06:48:36,455] {local_task_job.py:151} INFO - Task exited with return code 0
